---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cache
  namespace: flask-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-cache
  template:
    metadata:
      labels:
        name: flask-cache
      namespace: flask-cache
    spec:
      containers:
        - name: cache-service
          image: xasag94215/flask-cache
          ports:
            - containerPort: 5000
              name: rest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flask-cache-service
  namespace: flask-cache
spec:
  selector:
    name: flask-cache
  ports:
    - name: rest
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---

